name: optsimflex
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310h9128911_0
  - brotli-python=1.0.9=py310h8a704f9_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.7.22=h56e8100_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cycler=0.12.0=pyhd8ed1ab_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - filelock=3.12.4=pyhd8ed1ab_0
  - freetype=2.10.4=h546665d_1
  - giflib=5.2.1=h8d14728_2
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.37=pyhd8ed1ab_0
  - gymnasium=0.28.1=py310hbbfc1a7_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intel-openmp=2023.2.0=h57928b3_50496
  - ipykernel=6.25.2=pyh60829e3_0
  - ipython=8.16.1=pyh5737063_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h8ffe710_2
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py310h5588dad_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h8ffe710_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib-base=3.4.3=py310h79a7439_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.2.0=h6a75c08_50496
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - numexpr=2.8.4=py310h2cd9be0_1
  - numpy=1.26.0=py310h055cbcc_0
  - numpy-base=1.26.0=py310h65a83cf_0
  - openssl=3.0.11=h2bbff1b_2
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.5.3=py310h4ed8f06_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310hd77b12b_1
  - pip=23.2.1=py310haa95532_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=3.20.3=py310h5588dad_1
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.12=he1021f5_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=cpu_py310hb0bdfb8_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32=305=py310h2bbff1b_0
  - pyyaml=6.0=py310he2412df_4
  - requests=2.31.0=pyhd8ed1ab_0
  - scipy=1.11.1=py310h309d312_0
  - seaborn=0.12.2=py310haa95532_0
  - sentry-sdk=1.31.0=pyhd8ed1ab_0
  - setproctitle=1.2.2=py310he2412df_2
  - setuptools=68.0.0=py310haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.41.2=h2bbff1b_0
  - stable-baselines3=2.1.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py310he2412df_0
  - traitlets=5.11.2=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=2.0.6=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wandb=0.15.12=pyhd8ed1ab_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - wheel=0.41.2=py310haa95532_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xz=5.4.2=h8cc25b3_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cachetools==5.3.1
      - defusedxml==0.7.1
      - fastjsonschema==2.18.1
      - fqdn==1.5.1
      - google-auth==2.23.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.0
      - heapdict==1.0.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - markdown==3.4.4
      - mistune==3.0.2
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - notebook==7.0.4
      - notebook-shim==0.2.3
      - oauthlib==3.2.2
      - overrides==7.4.0
      - pandocfilters==1.5.0
      - prometheus-client==0.17.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - python-json-logger==2.0.7
      - pywinpty==2.0.11
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.4
      - rsa==4.9
      - sb3-contrib==2.1.0
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tomli==2.0.1
      - types-python-dateutil==2.8.19.14
      - uri-template==1.3.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - werkzeug==3.0.0
      - widgetsnbextension==4.0.9
prefix: C:\Users\notebook-heitor\anaconda3\envs\optsimflex
