wandb_version: 1

batch_size:
  desc: null
  value: 128
ent_coef:
  desc: null
  value: 0.0011272901084189424
gae_lambda:
  desc: null
  value: 0.9596952719973046
gamma:
  desc: null
  value: 0.8753942350770707
learning_rate:
  desc: null
  value: 0.0004601558914391742
n_epochs:
  desc: null
  value: 26
n_steps:
  desc: null
  value: 1536
target_kl:
  desc: null
  value: 0.012721791546567416
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696568500.933348
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 34
      - 37
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    session_history: code\_session_history.ipynb
