wandb_version: 1

atraso:
  desc: null
  value: -1
batch_size:
  desc: null
  value: 256
ent_coef:
  desc: null
  value: 0.001641577520175419
gae_lambda:
  desc: null
  value: 0.9142950466044
gamma:
  desc: null
  value: 0.918623650457886
learning_rate:
  desc: null
  value: 0.0003660144793262825
n_epochs:
  desc: null
  value: 21
n_steps:
  desc: null
  value: 3328
target_kl:
  desc: null
  value: 0.02113910446426361
_wandb:
  desc: null
  value:
    code_path: code/Treinamento.py
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696528643.151819
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 34
      4: 3.11.5
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
